.TH RMENU 1
.SH NAME
rmenu \- dmenu in rust
.SH SYNOPSIS
\fBrmenu\fR [FLAGS] [OPTIONS]
.SH DESCRIPTION
rmenu is a dynamic menu implemented for Redox, which reads a list of newline\-separated items from stdin. When the user selects an item and presses Return, their choice is printed to stdout and rmenu terminates. Entering text will narrow the items to those matching the tokens in the input. Default behaviour is to list programs in the user's $PATH and run the result in $SHELL, unless  user pipes in input.
.SH FLAGS
.TP
\fB\-b\fR
rmenu appears at the bottom of the screen.

.TP
\fB\-i\fR
rmenu matches menu items case insensitively.
.SH OPTIONS
.TP
\fB\-l\fR=\fIlines\fR
rmenu lists items vertically, with the given number of lines.

.TP
\fB\-p\fR=\fIprompt\fR
defines the prompt to be displayed to the left of the input field.
.SH EXAMPLES
.TP

\fB$ rmenu\fR
.br
Grants user a selection of programs in $PATH. When result is selected with Enter, program will run.
.TP

\fB$ echo "option 1\\noption2\\n option3" | rmenu \-l 3\fR
.br
Opens a menu from piped input seperated by newlines, displaying options vertically.

.SH AUTHOR
.P
.RS 2
.nf
Knarkzel <knarkzel@knarkzel.xyz>
